//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LauncherServer.Resources.NomRecursos {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class NomJson {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal NomJson() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LauncherServer.Resources.NomRecursos.NomJson", typeof(NomJson).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ListaCliente_Maquina.json.
        /// </summary>
        internal static string ClientesMaquina {
            get {
                return ResourceManager.GetString("ClientesMaquina", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a LauncherRamses.exe.
        /// </summary>
        internal static string ExeCliente {
            get {
                return ResourceManager.GetString("ExeCliente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a UpdarteLauncherRms.exe.
        /// </summary>
        internal static string ExeUpdate {
            get {
                return ResourceManager.GetString("ExeUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ListaNegra_servidor.json.
        /// </summary>
        internal static string JsonListaNegra {
            get {
                return ResourceManager.GetString("JsonListaNegra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a modulos_PDF.json.
        /// </summary>
        internal static string JsonPdfRms {
            get {
                return ResourceManager.GetString("JsonPdfRms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a modulos_servidor.json.
        /// </summary>
        internal static string JsonServerRms {
            get {
                return ResourceManager.GetString("JsonServerRms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ListaNegra_Extenciones.json.
        /// </summary>
        internal static string ListaNegraExtenciones {
            get {
                return ResourceManager.GetString("ListaNegraExtenciones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ListaNegra_ExtencionesBase.json.
        /// </summary>
        internal static string ListaNegraExtencionesBase {
            get {
                return ResourceManager.GetString("ListaNegraExtencionesBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a LauncherRamses.exe.
        /// </summary>
        internal static string NomProyecto {
            get {
                return ResourceManager.GetString("NomProyecto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a CrearReglas.bat.
        /// </summary>
        internal static string NomReglaBat {
            get {
                return ResourceManager.GetString("NomReglaBat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a TCPLaucherRamses.
        /// </summary>
        internal static string NomReglaTCP {
            get {
                return ResourceManager.GetString("NomReglaTCP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a UDPLaucherRamses.
        /// </summary>
        internal static string NomReglaUDP {
            get {
                return ResourceManager.GetString("NomReglaUDP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a HKEY_CURRENT_USER\Software\LauncherServer.
        /// </summary>
        internal static string PathRegistro {
            get {
                return ResourceManager.GetString("PathRegistro", resourceCulture);
            }
        }
    }
}
