//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LauncherServer.Resources.NomRecursos {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class NomKeyConfig {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal NomKeyConfig() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LauncherServer.Resources.NomRecursos.NomKeyConfig", typeof(NomKeyConfig).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a directoryPDF.
        /// </summary>
        internal static string DirectoryPDF {
            get {
                return ResourceManager.GetString("DirectoryPDF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a directoryRamses.
        /// </summary>
        internal static string DirectoryRms {
            get {
                return ResourceManager.GetString("DirectoryRms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ejecutableRms.
        /// </summary>
        internal static string EjecutableRms {
            get {
                return ResourceManager.GetString("EjecutableRms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a iplocal.
        /// </summary>
        internal static string IPlocal {
            get {
                return ResourceManager.GetString("IPlocal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a MinContingencia.
        /// </summary>
        internal static string MinContingencia {
            get {
                return ResourceManager.GetString("MinContingencia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a MinActualizaJson.
        /// </summary>
        internal static string MinJson {
            get {
                return ResourceManager.GetString("MinJson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a portserver.
        /// </summary>
        internal static string PortServer {
            get {
                return ResourceManager.GetString("PortServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a UrlRmsUpdate.
        /// </summary>
        internal static string UrlRmsUpdate {
            get {
                return ResourceManager.GetString("UrlRmsUpdate", resourceCulture);
            }
        }
    }
}
